In [1]:
# mike babb
# created: 2026 08 23
# find five groups of five letters

In [2]:
# standard
import pickle
import os
import sqlite3
from string import ascii_lowercase
from itertools import product, permutations, combinations

In [3]:
import pandas as pd
import numpy as np
import networkx as nx

In [4]:
# define a function to load a pickle
def load_pickle(file_name):
    if os.path.exists(file_name):
        with open(file_name, 'rb') as handle:
            de_pickle = pickle.load(handle)
    else:
        de_pickle = None
        print("file does not exist")
    return de_pickle

In [5]:
char_matrix = load_pickle(file_name = 'char_matrix.pkl')
letter_dict = load_pickle(file_name = 'letter_dict.pkl')
letter_rank_dict = load_pickle(file_name ='letter_rank_dict.pkl')
word_df = load_pickle(file_name = 'word_df.pkl')

C:\Users\babbm\AppData\Local\Temp\ipykernel_46572\773985408.py:5: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  de_pickle = pickle.load(handle)

In [6]:
word_df.head()

    word  lcase  word_id  n_unique_chars  word_score           word_group
0  aalii  aalii        0               3     20449.0 -2134795976539657997
1  Aaron  aaron        1               4     20642.0  5168226787426640364
2  abaca  abaca        2               3     20009.0  7298090979578241273
3  aback  aback        3               4     15456.0  6926502400987240042
4  abaff  abaff        4               3     14038.0  7931255010571806167

In [7]:
word_df.shape

(9972, 6)

In [8]:
# using the word_group, select entries
word_df = word_df.drop_duplicates(subset = ['word_group'])

In [9]:
word_df = word_df.loc[word_df['n_unique_chars'] == 5, :].sort_values(by = 'lcase').reset_index(drop = True)

In [10]:
word_df.head()

    word  lcase  word_id  n_unique_chars  word_score           word_group
0  abhor  abhor       22               5     15210.0 -6309929865134252395
1  abide  abide       23               5     16642.0 -3047576767538267104
2  Abies  abies       25               5     17816.0  7894952363982762409
3  abilo  abilo       26               5     16157.0 -4762514508553607400
4  abler  abler       28               5     17943.0 -7669602973530280345

In [11]:
word_df['word_id'] = range(0, word_df.shape[0])

In [12]:
word_id_list = word_df['word_id'].to_numpy(dtype = np.int16)

In [13]:
word_id_list

array([   0,    1,    2, ..., 4350, 4351, 4352],
      shape=(4353,), dtype=int16)

In [14]:
word_df['lcase'].map(lambda x: len(set(x))).describe()

count    4353.0
mean        5.0
std         0.0
min         5.0
25%         5.0
50%         5.0
75%         5.0
max         5.0
Name: lcase, dtype: float64

In [15]:
# build a char_matrix
char_matrix = np.zeros(shape = (word_df.shape[0], 26), dtype = np.int8)
def build_char_matrix(row):
    word = sorted(row['lcase'])
    for iw, w in enumerate(word):
        char_matrix[row['word_id'], letter_dict[w]] += 1

In [16]:
outcome = word_df.apply(build_char_matrix, axis = 1)

In [17]:
char_matrix

array([[1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 1]], shape=(4353, 26), dtype=int8)

In [18]:
char_matrix.max()

np.int8(1)

In [19]:
assert word_df.shape[0] == char_matrix.shape[0]

In [20]:
char_matrix.shape

(4353, 26)

In [21]:
# a solution
# vibex glyph muntz dwarf jocks

In [22]:
word_df['lcase_set'] = word_df['lcase'].map(lambda x: set(x))
word_df['lcase_tuple'] = word_df['lcase_set'].map(lambda x: tuple(x))

In [23]:
# build dictionaries
word_dict = {}
for i_row, my_row in word_df.iterrows():
    word_dict[my_row['lcase']] = my_row['lcase_set']

In [24]:
lc_set = set(ascii_lowercase)

In [25]:
vowel_set = set('aeiouy')

In [26]:
edge_list = []
for lc0, lc1 in combinations(word_df['lcase'], 2):
    w1w2_set = word_dict[lc0].union(word_dict[lc1])    
    if len(w1w2_set) == 10:

        # compute the number of vowels left over
        remaining_vowels = vowel_set.difference(w1w2_set)
        # need at least three vowels - for three separate words to continue
        if len(remaining_vowels) >= 3:
            
            existing_letters = ''.join(sorted(w1w2_set))
            remainder_letters = ''.join(sorted(lc_set.difference(existing_letters)))

            ##edge_list.append([ms[0], ms[1]])
            edge_list.append([lc0, lc1, existing_letters, remainder_letters ])
            #myg.add_edge(u_of_edge=lc0, v_of_edge=lc1)

In [27]:
# export to an edgelist
output = pd.DataFrame(data = edge_list, columns = ['w1', 'w2', 'l2_existing', 'r2_remainder'])

In [28]:
output.shape

(502235, 4)

In [29]:
output.head()

      w1     w2 l2_existing      r2_remainder
0  abhor  cleft  abcefhlort  dgijkmnpqsuvwxyz
1  abhor  clift  abcfhilort  degjkmnpqsuvwxyz
2  abhor  cling  abcghilnor  defjkmpqstuvwxyz
3  abhor  clink  abchiklnor  defgjmpqstuvwxyz
4  abhor  clint  abchilnort  defgjkmpqsuvwxyz

In [30]:
remainder = output.drop_duplicates(subset = ['l2_existing', 'r2_remainder'])

In [31]:
remainder.shape

(185268, 4)

In [32]:
remainder.head()

      w1     w2 l2_existing      r2_remainder
0  abhor  cleft  abcefhlort  dgijkmnpqsuvwxyz
1  abhor  clift  abcfhilort  degjkmnpqsuvwxyz
2  abhor  cling  abcghilnor  defjkmpqstuvwxyz
3  abhor  clink  abchiklnor  defgjmpqstuvwxyz
4  abhor  clint  abchilnort  defgjkmpqsuvwxyz

In [33]:
test_df = remainder.iloc[:1000]

In [34]:
working_word_df = word_df[['word_id', 'lcase']].copy()

In [35]:
def get_vowels(letters, r_word, min_vowel_count, existing_words):    

    # combine the l1 and the lcase to make l2
    letter_group = set(letters + r_word)
    rg_vowels = vowel_set.difference(letter_group)
    rg_vowel_count = len(rg_vowels)    

    if rg_vowel_count >= min_vowel_count:        
        letter_group = ''.join(sorted(letter_group))    
        remainder_group  = lc_set.difference(letter_group)
        remainder_group = ''.join(sorted(remainder_group))
        temp_list = [r_word, letter_group, remainder_group]
        existing_words.extend(temp_list)
        return existing_words
    else:
        return None

In [36]:
working_word_df = word_df[['word_id', 'lcase']].copy()

In [37]:
l3_df_list = []
for i_row, row in remainder.iterrows():
    
    w1, w2, l2, r2 = row
    # existing letters
    existing_id_list = []
    for l in l2:
        l_idx = letter_dict[l]   
        test_char_matrix = char_matrix[:, l_idx] == 1
        # print(word_id_list[test_char_matrix])
        existing_id_list.append(word_id_list[test_char_matrix])

    #print(inclusive_id_list)
    existing_id_list = np.concatenate(existing_id_list)
    

    remainder_id_list = np.setdiff1d(word_id_list, existing_id_list)
    if remainder_id_list.size > 0:                
    
        # do this later - winnow down the set list sooner
        r3_word_list = working_word_df.loc[working_word_df['word_id'].isin(remainder_id_list), 'lcase'].tolist()
        # print(r3_word_list)
        for r3_word in r3_word_list:
            output = get_vowels(letters=l2, r_word = r3_word, min_vowel_count=2, existing_words=[w1, w2])
            if output:
                l3_df_list.append(output)

In [38]:
l3_df = pd.DataFrame(data = l3_df_list, columns = ['w1', 'w2', 'w3', 'l3', 'r3'])

In [39]:
l3_df.head()

      w1     w2     w3               l3           r3
0  abhor  cleft  dimps  abcdefhilmoprst  gjknquvwxyz
1  abhor  cleft  jinks  abcefhijklnorst  dgmpquvwxyz
2  abhor  cleft  skimp  abcefhiklmoprst  dgjnquvwxyz
3  abhor  cleft  spink  abcefhiklnoprst  dgjmquvwxyz
4  abhor  cleft  spung  abcefghlnoprstu  dijkmqvwxyz

In [40]:
l3_df.shape

(4950787, 5)

In [41]:
test_df = l3_df[['w1', 'w2', 'w3', 'l3', 'r3']].drop_duplicates(subset = ['l3', 'r3'] )

In [42]:
test_df.shape

(233091, 5)

In [43]:
test_df.head()

      w1     w2     w3               l3           r3
0  abhor  cleft  dimps  abcdefhilmoprst  gjknquvwxyz
1  abhor  cleft  jinks  abcefhijklnorst  dgmpquvwxyz
2  abhor  cleft  skimp  abcefhiklmoprst  dgjnquvwxyz
3  abhor  cleft  spink  abcefhiklnoprst  dgjmquvwxyz
4  abhor  cleft  spung  abcefghlnoprstu  dijkmqvwxyz

In [44]:
level3_list = []
l4_df_list = []
for i_row, row in test_df.iterrows():

    w1, w2, w3, l3, r3 = row

    # existing letters
    existing_id_list = []
    for l in l3:
        l_idx = letter_dict[l]   
        test_char_matrix = char_matrix[:, l_idx] == 1
        # print(word_id_list[test_char_matrix])
        existing_id_list.append(word_id_list[test_char_matrix])

    #print(inclusive_id_list)
    existing_id_list = np.concatenate(existing_id_list)        
    
    remainder_id_list = np.setdiff1d(word_id_list, existing_id_list)
    if remainder_id_list.size > 0:                
        #print(l1, r1, outcome_ids.shape)        
        #level2_list.append([l1, r1, existing_id_list.shape[0], remainder_id_list.shape[0]])                       
        #         
        # l1
        # do this later - winnow down the set list sooner
        # do this later - winnow down the set list sooner
        r4_word_list = working_word_df.loc[working_word_df['word_id'].isin(remainder_id_list), 'lcase'].tolist()
        # print(r3_word_list)
        for r4_word in r4_word_list:
            output = get_vowels(letters=l3, r_word = r4_word, min_vowel_count=1, existing_words=[w1, w2, w3])
            if output:
                l4_df_list.append(output)

In [45]:
l4_df = pd.DataFrame(data = l4_df_list, columns =  ['w1', 'w2', 'w3', 'w4', 'l4', 'r4'])

In [49]:
l4_df.shape

(231503, 6)

In [50]:
l4_df.head()

      w1     w2     w3     w4                    l4      r4
0  abhor  fjeld  spung  twick  abcdefghijklnoprstuw  mqvxyz
1  abhor  fjeld  twick  spung  abcdefghijklnoprstuw  mqvxyz
2  abhor  spung  twick  fjeld  abcdefghijklnoprstuw  mqvxyz
3  abler  pfund  smock  wight  abcdefghiklmnoprstuw  jqvxyz
4  abler  pfund  wight  smock  abcdefghiklmnoprstuw  jqvxyz

In [51]:
test_df = l4_df.drop_duplicates(subset = ['l4', 'r4'])

In [52]:
test_df.shape

(6368, 6)

In [57]:
test_df.to_excel('level_4.xlsx', index = False)

In [53]:
l5_df_list = []
for i_row, row in test_df.iterrows():
    print(i_row)

    w1, w2, w3, w4, l4, r4 = row

    # existing letters
    existing_id_list = []
    for l in l4:
        l_idx = letter_dict[l]   
        test_char_matrix = char_matrix[:, l_idx] == 1
        # print(word_id_list[test_char_matrix])
        existing_id_list.append(word_id_list[test_char_matrix])

    #print(inclusive_id_list)
    existing_id_list = np.concatenate(existing_id_list)        
    
    remainder_id_list = np.setdiff1d(word_id_list, existing_id_list)
    if remainder_id_list.size > 0:                
        #print(l1, r1, outcome_ids.shape)        
        #level2_list.append([l1, r1, existing_id_list.shape[0], remainder_id_list.shape[0]])                       
        #         
        # l1
        # do this later - winnow down the set list sooner
        # do this later - winnow down the set list sooner
        r5_word_list = working_word_df.loc[working_word_df['word_id'].isin(remainder_id_list), 'lcase'].tolist()
        # print(r3_word_list)
        for r5_word in r5_word_list:
            output = get_vowels(letters=l4, r_word = r5_word, min_vowel_count=0, existing_words=[w1, w2, w3, w4])
            if output:
                l5_df_list.append(output)

0
3
6
9
13
15
19
20
44
47
50
57
60
63
69
77
88
90
91
92
100
111
112
113
115
116
121
123
124
126
156
210
240
250
252
255
257
261
266
269
270
300
351
353
370
371
373
375
379
381
383
391
393
415
438
443
446
447
449
456
462
463
504
511
520
560
570
571
572
576
583
584
592
598
599
601
602
603
611
618
642
643
663
668
669
670
671
673
679
681
682
685
686
687
692
696
727
741
742
745
746
749
767
772
773
782
784
786
795
797
800
822
825
826
828
829
830
832
833
834
835
836
837
840
842
843
844
848
852
853
855
857
885
886
888
905
920
929
939
940
965
966
986
1002
1039
1054
1081
1090
1101
1134
1136
1187
1193
1194
1195
1208
1213
1225
1231
1260
1261
1272
1273
1274
1275
1276
1278
1301
1359
1538
1557
1682
1691
1692
1701
1704
1711
1713
1738
1742
1744
1753
1754
1756
1773
1815
1816
1818
1843
1847
1884
1901
1920
1921
1923
1949
1951
1952
1967
2064
2065
2066
2103
2133
2135
2174
2199
2236
2264
2349
2355
2374
2448
2456
2482
2529
2539
2541
2548
2555
2582
2610
2614
2636
2651
2693
2700
2703
2705
2710
2735
2769
2781
2783
2784
2791
2820
2827
2834
2866
2872
2874
2894
2902
2971
3003
3011
3012
3018
3067
3073
3083
3095
3115
3129
3159
3194
3196
3220
3221
3231
3233
3256
3270
3271
3275
3313
3315
3320
3322
3329
3355
3365
3383
3384
3397
3419
3420
3421
3424
3425
3444
3446
3447
3448
3455
3457
3463
3472
3474
3475
3476
3477
3481
3482
3484
3486
3487
3488
3489
3490
3498
3499
3500
3501
3502
3503
3504
3505
3525
3531
3569
3571
3572
3573
3574
3583
3586
3587
3589
3605
3608
3609
3610
3611
3612
3619
3648
3652
3658
3662
3670
3672
3680
3681
3691
3700
3727
3730
3735
3754
3756
3757
3758
3760
3772
3809
3815
3823
3832
3847
3856
3870
3872
3873
3874
3875
3876
3877
3878
3898
3902
3903
3939
3941
3945
3949
3953
3966
3973
3989
4007
4027
4037
4039
4040
4041
4092
4102
4105
4106
4107
4108
4110
4111
4112
4113
4114
4115
4117
4120
4121
4125
4127
4132
4142
4146
4154
4160
4171
4172
4176
4178
4181
4186
4189
4194
4195
4196
4197
4198
4199
4200
4201
4202
4203
4204
4205
4206
4208
4209
4210
4221
4229
4230
4233
4235
4297
4298
4300
4303
4304
4314
4315
4333
4335
4337
4421
4424
4450
4451
4452
4468
4472
4474
4479
4484
4493
4518
4520
4533
4534
4542
4544
4550
4560
4569
4570
4572
4574
4595
4599
4640
4649
4652
4653
4657
4674
4681
4682
4684
4687
4690
4691
4694
4695
4696
4697
4699
4707
4710
4720
4727
4731
4741
4744
4745
4746
4750
4751
4761
4763
4766
4770
4778
4790
4806
4809
4811
4821
4828
4831
4850
4851
4852
4864
4865
4866
4867
4868
4873
4879
4886
4888
4889
4893
4894
4898
4905
4912
4915
4925
4926
4935
4938
4942
4944
4946
4955
4956
4957
4959
4960
4961
4962
4966
4967
4972
4978
4988
5005
5007
5010
5012
5013
5020
5045
5050
5063
5075
5078
5096
5100
5102
5139
5153
5154
5266
5284
5285
5286
5334
5350
5351
5354
5355
5375
5477
5509
5534
5536
5552
5566
5567
5568
5569
5570
5571
5572
5573
5576
5578
5579
5584
5586
5589
5590
5596
5598
5599
5600
5612
5613
5614
5615
5616
5636
5713
5726
5735
5772
5773
5774
5826
5888
6019
6054
6064
6113
6122
6126
6150
6158
6229
6231
6235
6247
6265
6419
6420
6456
6466
6497
6514
6665
6673
6676
6677
6678
6685
6686
6687
6688
6689
6690
6704
6706
6708
6750
6758
6760
6762
6763
6766
6768
6771
6777
6786
6806
6835
6837
6844
6845
6851
6891
6895
6897
6909
6917
6918
6923
6928
6930
6931
6933
6934
6938
6944
6945
6961
6965
6968
6969
6971
6972
6986
6993
7007
7013
7014
7015
7018
7019
7034
7046
7049
7055
7056
7059
7068
7077
7083
7088
7089
7096
7103
7104
7105
7109
7110
7121
7137
7141
7146
7149
7156
7159
7181
7182
7208
7209
7210
7212
7223
7225
7230
7234
7236
7265
7266
7268
7275
7277
7278
7289
7292
7294
7314
7315
7316
7317
7319
7320
7337
7338
7340
7369
7385
7392
7393
7407
7408
7455
7460
7465
7473
7481
7500
7501
7518
7519
7520
7521
7535
7536
7565
7566
7649
7664
7743
7797
7863
7895
7907
7917
7934
7935
7958
8018
8022
8028
8031
8037
8038
8039
8040
8041
8043
8044
8045
8046
8048
8051
8054
8060
8075
8083
8084
8085
8086
8088
8089
8090
8096
8097
8098
8108
8109
8113
8114
8115
8116
8117
8125
8128
8130
8155
8162
8169
8170
8171
8172
8173
8174
8175
8176
8178
8179
8189
8190
8196
8200
8201
8203
8212
8217
8270
8276
8280
8307
8314
8317
8318
8337
8343
8355
8443
8475
8497
8527
8530
8544
8545
8599
8600
8601
8624
8626
8627
8643
8658
8686
8729
8742
8756
8794
8799
8813
8823
8858
8860
8863
8866
8896
8907
8944
8972
9005
9029
9035
9075
9076
9161
9208
9209
9211
9216
9242
9268
9269
9280
9281
9282
9283
9371
9375
9414
9439
9445
9449
9451
9481
9482
9584
9629
9631
9670
9721
9764
9775
9778
9810
9825
9931
9947
9956
10010
10018
10062
10067
10093
10105
10108
10113
10114
10174
10175
10177
10240
10280
10296
10315
10338
10463
10464
10465
10466
10467
10491
10599
10601
10660
10661
10662
10663
10664
10700
10711
10727
10732
10747
10759
10772
10794
10801
10832
10837
10845
10854
10880
10884
10916
10920
10948
10953
10954
11066
11074
11092
11109
11114
11118
11143
11144
11145
11146
11147
11148
11160
11164
11165
11196
11224
11225
11234
11249
11250
11342
11346
11430
11438
11483
11489
11499
11508
11513
11514
11519
11520
11524
11531
11546
11555
11556
11557
11566
11567
11572
11575
11580
11585
11615
11627
11629
11660
11670
11689
11700
11704
11705
11706
11708
11713
11737
11739
11756
11758
11759
11760
11766
11770
11805
11812
11814
11856
11860
11862
11867
11880
11881
11883
11884
11899
11900
11920
11922
11927
11929
11933
11999
12000
12029
12033
12044
12070
12071
12089
12098
12114
12118
12125
12131
12154
12175
12176
12177
12178
12179
12180
12181
12203
12210
12230
12237
12253
12262
12310
12352
12354
12359
12361
12385
12386
12396
12400
12407
12410
12454
12456
12479
12480
12484
12488
12494
12499
12508
12542
12550
12566
12568
12582
12585
12589
12608
12611
12778
12792
12807
12809
12812
12815
12837
12845
12850
12858
12859
12876
12878
12880
12891
12892
12926
12932
12941
12957
12961
12974
13019
13026
13102
13115
13120
13125
13138
13147
13157
13185
13215
13216
13232
13234
13269
13281
13347
13355
13356
13357
13358
13362
13368
13371
13375
13376
13379
13394
13405
13406
13411
13412
13415
13422
13434
13470
13483
13531
13569
13573
13612
13642
13680
13683
13699
13700
13727
13729
13780
13798
13804
13820
13831
13938
13960
13962
13975
13982
14007
14033
14055
14063
14096
14097
14114
14126
14138
14143
14170
14188
14195
14206
14222
14324
14344
14428
14430
14447
14592
14613
14614
14615
14631
14642
14649
14650
14658
14661
14662
14663
14688
14694
14696
14699
14745
14776
14907
14910
14912
14913
14921
14922
14966
14978
14981
14990
14992
15004
15046
15053
15055
15058
15071
15087
15088
15098
15101
15126
15135
15148
15149
15155
15165
15189
15193
15194
15213
15233
15235
15241
15242
15243
15255
15285
15286
15287
15290
15291
15315
15339
15379
15381
15382
15383
15384
15385
15386
15387
15388
15389
15390
15402
15506
15514
15529
15531
15548
15562
15565
15566
15622
15728
15731
15763
15863
16074
16092
16150
16258
16265
16315
16356
16357
16360
16361
16363
16775
16801
16807
16824
16852
16856
16876
16887
16888
16942
16944
16969
17006
17008
17083
17101
17298
17428
17448
17477
17580
17655
17694
17736
17746
17773
17817
17885
17890
17905
17906
17986
18017
18032
18034
18035
18036
18037
18060
18061
18062
18089
18091
18093
18094
18095
18114
18116
18174
18186
18255
18276
18287
18289
18297
18306
18335
18336
18370
18371
18391
18458
18485
18498
18506
18546
18569
18606
18615
18652
18676
18683
18685
18687
18689
18691
18720
18722
18728
18745
18747
18754
18755
18756
18757
18868
18879
18880
18881
18915
18940
18955
18956
18957
19005
19019
19129
19162
19173
19185
19221
19222
19238
19239
19263
19266
19272
19314
19344
19345
19372
19414
19416
19498
19510
19606
19633
19648
19651
19697
19698
19699
19702
19703
19704
19705
19706
19707
19708
19709
19710
19726
19728
19729
19730
19731
19732
19733
19734
19807
19853
19888
19901
19902
20023
20024
20027
20036
20037
20057
20071
20084
20098
20100
20150
20185
20220
20233
20236
20557
20583
20649
20652
20669
20671
20680
20690
20731
20760
20796
20811
20812
20814
20823
20861
20893
20906
20909
20921
20930
20940
20941
20943
20944
20945
20951
20964
20990
20994
20995
20996
20998
20999
21000
21001
21002
21003
21004
21009
21035
21062
21064
21106
21114
21159
21160
21185
21331
21438
21462
21463
21466
21495
21502
21532
21557
21581
21584
21585
21586
21591
21601
21614
21617
21666
21673
21679
21680
21745
21746
21751
21754
21778
21796
21845
21870
21871
21872
21880
21881
21994
22035
22048
22127
22142
22167
22171
22172
22243
22382
22391
22393
22409
22420
22436
22437
22454
22676
22677
22789
22873
22888
22889
22892
22895
22897
22939
22941
22947
22951
22962
22988
23003
23032
23034
23035
23037
23038
23039
23040
23041
23058
23060
23061
23132
23135
23136
23139
23189
23211
23212
23244
23246
23382
23413
23506
23629
23634
23636
23646
23655
23660
23662
23669
23671
23672
23680
23686
23698
23700
23702
23721
23723
23725
23729
23739
23743
23751
23756
23757
23762
23768
23775
23799
23813
23815
23818
23819
23831
23833
23835
23847
23859
23860
23866
23869
23883
23898
23908
23913
23957
23965
23967
23969
23973
23974
23976
23979
23980
24072
24079
24081
24088
24165
24306
24323
24326
24327
24329
24334
24373
24390
24416
24418
24488
24494
24495
24498
24517
24518
24520
24521
24523
24577
24578
24589
24592
24606
24633
24640
24675
24681
24682
24684
24722
24732
24736
24739
24740
24788
24792
24793
24794
24799
24801
24802
24860
24864
24871
24872
24903
24905
24907
24908
24912
24975
24984
24992
25021
25030
25031
25032
25033
25034
25035
25036
25037
25038
25039
25052
25141
25142
25143
25152
25154
25160
25185
25192
25195
25196
25197
25198
25199
25200
25201
25202
25258
25345
25346
25349
25350
25352
25385
25388
25389
25411
25420
25435
25464
25468
25469
25481
25513
25514
25569
25577
25579
25581
25590
25593
25594
25603
25625
25651
25740
25756
25781
25789
26002
26034
26070
26076
26077
26083
26085
26086
26124
26151
26160
26173
26695
26730
26746
26769
26954
26990
27002
27133
27176
27270
27278
27281
27282
27303
27308
27309
27314
27315
27318
27323
27333
27334
27347
27368
27376
27383
27395
27403
27404
27405
27414
27418
27429
27481
27507
27511
27515
27526
27527
27563
27577
27587
27664
27700
27718
27723
27724
27726
27727
27728
27820
27825
27842
27845
27846
27854
27855
27865
27912
27927
27929
27937
27954
27975
27987
27998
28002
28003
28066
28110
28111
28125
28126
28130
28131
28206
28228
28241
28304
28313
28319
28323
28335
28362
28373
28387
28396
28397
28416
28423
28425
28437
28438
28490
28507
28516
28622
28649
28737
28744
28752
28761
28764
28785
28792
28900
28982
29000
29004
29005
29006
29109
29127
29128
29147
29200
29204
29221
29222
29224
29284
29297
29300
29310
29355
29366
29369
29374
29409
29416
29418
29447
29469
29522
29537
29561
29567
29568
29570
29573
29575
29682
29684
29691
29692
29714
29715
29716
29721
29723
29724
29736
29748
29764
29788
29799
29814
29840
29854
29924
29935
29936
29937
29938
29970
29992
29993
30010
30067
30090
30148
30160
30162
30175
30186
30247
30288
30299
30303
30304
30306
30307
30309
30310
30313
30368
30370
30394
30402
30403
30411
30426
30437
30455
30457
30459
30463
30465
30468
30470
30471
30488
30489
30493
30495
30534
30548
30553
30602
30730
30732
30752
30756
30847
30863
30890
30904
30928
30936
30937
30952
30954
31092
31123
31133
31134
31160
31196
31436
31437
31438
31464
31465
31561
31570
31583
31629
31639
31698
31705
31706
31707
31717
31768
31806
31816
31821
31823
31832
31863
31886
31887
31889
31892
31910
31915
31921
31922
31927
31970
31988
31993
32016
32074
32075
32078
32154
32173
32235
32249
32251
32256
32258
32268
32275
32285
32287
32288
32334
32339
32340
32347
32386
32390
32396
32460
32480
32493
32532
32537
32553
32572
32635
32654
32662
32667
32728
32734
32771
32790
32985
33007
33008
33015
33027
33030
33049
33053
33076
33077
33112
33113
33117
33118
33213
33281
33294
33351
33353
33384
33421
33431
33458
33466
33467
33472
33474
33504
33505
33507
33615
33649
33694
33726
33727
33733
33792
33836
33844
33872
33892
33906
33948
33976
33977
33978
33979
33980
33981
34109
34202
34227
34236
34238
34240
34278
34314
34446
34463
34483
34503
34581
34595
34598
34935
34942
34952
34967
34989
35005
35007
35023
35030
35063
35065
35067
35090
35105
35106
35135
35136
35137
35679
35703
35727
35729
35753
35868
36070
36072
36073
36141
36145
36197
36366
36373
36412
36413
36452
36504
36506
36588
36594
36635
36734
36765
36946
36986
36993
37004
37032
37061
37086
37098
37110
37153
37184
37185
37187
37189
37229
37230
37231
37236
37242
37305
37338
37376
37490
37522
37527
37542
37558
37564
37589
37591
37600
37662
37690
37739
37742
38017
38076
38209
38275
38397
38398
38430
38460
38463
38596
38614
38615
38637
38638
38653
38680
38685
38724
38747
38778
38779
38780
38785
38816
38840
38844
38862
38863
38879
38890
38934
38942
38974
38994
39029
39046
39087
39095
39119
39126
39132
39133
39134
39136
39137
39161
39199
39205
39206
39218
39219
39220
39226
39230
39260
39269
39352
39353
39358
39385
39395
39407
39438
39470
39535
39554
39556
39559
39581
39582
39589
39667
39676
39702
39703
39714
39746
39749
39757
39764
39779
39849
39880
39896
39897
39953
39972
40048
40145
40283
40296
40309
40319
40344
40355
40379
40396
40397
40429
40437
40439
40440
40530
40581
40587
40594
40595
40608
40616
40628
40689
40692
40698
40719
40720
40724
40735
40736
40783
40794
40795
40810
40812
40814
40815
40827
40845
40878
40888
40902
40904
41105
41128
41147
41227
41271
41301
41317
41357
41386
41423
41425
41444
41463
41467
41480
41515
41538
41544
41547
41548
41584
41586
41597
41602
41614
41636
41637
41653
41696
41737
41738
41934
41937
41963
41977
42024
42065
42221
42256
42397
42409
42416
42457
42539
42554
42560
42613
42621
42639
42713
42717
42718
42730
42733
43058
43068
43117
43133
43137
43147
43161
43166
43169
43239
43251
43256
43278
43279
43293
43340
43373
43418
43442
43443
43506
43516
43525
43526
43541
43603
43654
43658
43730
43731
43789
43791
43824
43883
43913
43916
43917
43932
43948
43952
43953
43959
43989
43990
43996
43997
44003
44013
44021
44058
44067
44077
44081
44152
44159
44165
44166
44167
44168
44170
44172
44173
44174
44175
44178
44196
44197
44199
44200
44202
44204
44209
44215
44222
44226
44243
44259
44260
44328
44329
44330
44426
44450
44475
44477
44483
44697
44757
44784
44809
44917
45082
45266
45267
45277
45291
45292
45296
45323
45405
45450
45493
45523
45637
45673
45689
45708
45709
45710
45711
45712
45713
45714
45722
45726
45732
45737
45756
45900
45910
45942
45949
46121
46274
46290
46326
46328
46332
46335
46337
46338
46359
46466
46488
46507
46508
46516
46598
46614
46640
46766
46775
46776
46799
46802
46803
46821
46837
46848
46851
46853
46864
46875
46889
46898
46906
46944
46950
46957
46962
46964
46968
47009
47017
47039
47050
47051
47060
47132
47134
47157
47159
47160
47240
47281
47282
47318
47327
47367
47378
47383
47385
47387
47450
47462
47464
47466
47513
47546
47557
47558
47570
47573
47578
47590
47591
47653
47662
47684
47854
47857
47863
47948
48012
48019
48128
48185
48190
48231
48490
48497
48642
48679
48689
48723
48739
48804
48868
48915
48932
48961
49062
49076
49079
49080
49082
49189
49199
49207
49229
49234
49239
49289
49294
49310
49324
49381
49402
49495
49514
49561
49562
49589
49590
49596
49616
49664
49801
49874
49885
49903
49913
49914
49915
49916
49917
49918
49919
49942
49963
50032
50046
50150
50151
50152
50545
50546
50670
50848
50863
50884
50976
50977
50984
51007
51014
51028
51047
51051
51057
51339
51359
51380
51383
51404
51419
51455
51498
51509
51516
51587
51589
51593
51594
51604
51607
51616
51621
51623
51901
51931
51939
51940
51991
52010
52025
52054
52066
52071
52091
52093
52097
52105
52136
52147
52149
52150
52166
52224
52235
52236
52237
52251
52256
52257
52262
52266
52282
52308
52311
52312
52321
52370
52388
52390
52401
52468
52490
52491
52496
52549
52552
52565
52592
52729
52848
52861
52862
52863
52904
52975
52989
52997
53072
53097
53103
53129
53134
53138
53167
53174
53180
53193
53199
53234
53278
53279
53287
53288
53377
53472
53480
53490
53506
53552
53553
53634
53638
53689
53694
53695
53713
53714
53728
53729
53733
53736
53743
53750
53762
53780
53785
53791
53839
53841
53852
53868
53874
53876
53915
53958
54065
54069
54079
54221
54225
54259
54261
54334
54335
54346
54357
54375
54428
54434
54464
54489
54492
54504
54505
54515
54611
54622
54650
54652
54657
54658
54662
54663
54715
54720
54722
54723
54823
54831
54833
54834
54835
54839
54841
54842
54845
54850
54859
54873
54874
54994
55005
55006
55008
55009
55013
55051
55052
55053
55054
55060
55077
55078
55118
55289
55324
55382
55383
55384
55487
55510
55511
55544
55566
55568
55595
55635
55653
55661
55662
55665
55677
55838
55860
55867
55868
55869
55874
55927
55928
55933
55936
55941
55949
55951
55952
55953
55959
55960
55961
55962
55963
55964
55973
56001
56219
56244
56261
56262
56264
56265
56298
56332
56440
56442
56640
56651
56741
56817
56830
56833
56845
56846
56849
56850
56851
56856
56857
57112
57113
57116
57309
57587
57779
57790
57804
57868
57889
57917
57960
58026
58032
58035
58053
58054
58055
58068
58069
58137
58144
58156
58180
58181
58316
58318
58379
58467
58554
58571
58577
58691
58692
58699
58715
58752
58754
58756
58776
58848
58849
58906
58979
58999
59001
59006
59012
59028
59029
59076
59112
59132
59346
59452
59458
59548
59628
59799
59912
59925
59927
60011
60168
60206
60229
60271
60286
60287
60357
60437
60473
60488
60521
60528
60529
60545
60546
60686
60745
60747
60752
60789
60800
60846
60863
60870
60894
60901
60907
60941
60942
61207
61429
61485
61546
61591
61617
61725
61782
61792
61793
61803
61809
61848
61853
61854
61856
61857
61887
61893
61897
61923
61954
61964
61989
62009
62011
62031
62078
62095
62121
62123
62124
62125
62191
62197
62205
62206
62207
62208
62209
62210
62211
62220
62338
62349
62350
62510
62689
62707
62761
62769
62847
62878
62954
63161
63234
63263
63264
63290
63293
63365
63707
63789
63937
63949
64036
64079
64112
64141
64145
64226
64258
64262
64263
64264
64266
64271
64279
64286
64304
64308
64313
64314
64316
64321
64352
64384
64385
64401
64414
64415
64426
64457
64537
64538
64655
64679
64680
64681
64682
64685
64706
64707
64742
64781
64794
64820
64831
64872
64919
64922
64926
64932
64961
64962
64964
64977
65026
65042
65044
65266
65468
65471
65498
65529
65530
65533
65535
65536
65537
65539
65547
65551
65575
65597
65605
65606
65686
65693
65713
65745
65750
65768
65770
65796
65799
65802
65803
65804
65808
65812
65813
65817
65831
65832
65845
65862
65882
65901
65902
65922
65959
66013
66026
66054
66057
66063
66128
66129
66131
66132
66135
66143
66190
66224
66298
66318
66326
66333
66334
66335
66336
66487
66564
66602
66603
66607
66647
66658
66784
66794
66895
66900
66915
66923
66936
67005
67010
67141
67160
67175
67184
67193
67195
67200
67208
67209
67219
67369
67449
67507
67528
67530
67532
67579
67583
67591
67604
67608
67620
67650
67651
67667
67676
67718
67727
67728
67743
67798
67813
67875
67883
67884
67894
67901
67902
67903
67906
67920
67988
68063
68064
68122
68160
68220
68222
68224
68229
68242
68258
68266
68386
68388
68393
68401
68403
68457
68459
68461
68464
68465
68471
68485
68494
68496
68500
68519
68524
68528
68543
68575
68576
68577
68578
68579
68580
68598
68599
68621
68630
68637
68638
68639
68645
68648
68674
68675
68678
68679
68692
68704
68705
68738
68741
68749
68750
68751
68759
68760
68761
68763
68772
68774
68775
68776
68787
68815
68829
68847
68868
68872
68873
68902
68915
68916
68933
68967
68969
68979
68980
68987
68996
68997
69012
69025
69026
69039
69094
69133
69134
69158
69177
69439
69463
69489
69490
69491
69500
69515
69516
69517
69546
69554
69594
69653
69667
69723
69733
69736
69739
69857
69859
69860
69863
69864
69870
69885
69887
69889
69934
69935
70035
70056
70119
70120
70161
70216
70218
70250
70261
70292
70333
70344
70408
70410
70439
70486
70489
70524
70528
70629
70630
70633
70634
70670
70775
70785
70805
70813
70840
70842
70845
70847
70869
70897
70898
70900
70917
70950
70967
71035
71131
71140
71141
71142
71143
71148
71149
71150
71171
71174
71315
71482
71484
71489
71497
71505
71509
71661
71739
71758
71761
71762
71808
71830
71831
71842
71856
71918
72105
72141
72247
72302
72736
72749
72759
72760
72780
73728
73735
73774
73853
73878
73879
73899
73908
73909
73911
73971
74324
74325
74337
74506
74514
74725
74851
74934
74936
74949
75009
75022
75023
75024
75053
75074
75115
75219
75221
75628
75708
76009
76031
76045
76096
76097
76564
76569
76664
76675
76685
76703
76857
76884
76955
76962
76983
77016
77020
77155
77189
77195
77198
77203
77222
77248
77303
77307

In [54]:
l5_df = pd.DataFrame(data = l5_df_list, columns =  ['w1', 'w2', 'w3', 'w4', 'w5', 'l5', 'r5'])

In [56]:
l5_df.head()

Empty DataFrame
Columns: [w1, w2, w3, w4, w5, l5, r5]
Index: []

In [ ]:
l2_words['l2'].unique().shape

In [ ]:
sc_df['inclusive_diff'] = sc_df['inclusive'] + sc_df['outcome']

In [ ]:
sc_df

In [ ]:
sc_df['inclusive_diff'].describe()

In [ ]:
np.unique(inclusive_id_list).shape

In [ ]:
np.unique(remainder_id_list).shape

In [ ]:
outcome_ids = np.setdiff1d(remainder_id_list, inclusive_id_list)

In [ ]:
outcome_ids

In [ ]:
char_index_vector = [letter_dict[x] for x in l1]

In [ ]:
char_index_vector

In [ ]:
char_matrix.sum()

In [ ]:
for x in lett

In [ ]:
testo = char_matrix[:, char_index_vector].sum(axis = 1) > 0

In [ ]:
testo.sum()

In [ ]:
testo.shape

In [ ]:
def create_1d_vector(letters):
    output = np.zeros((26,), dtype = np.int8)
    for l in letters:
        output[letter_dict[l]] = 1
    return output

In [ ]:
l1_v = create_1d_vector(letters = remainder['letters'].iloc[0])
l1_v

In [ ]:
outcome = (char_matrix + l1_v)

In [ ]:
outcome

In [ ]:
(outcome.max(axis = 1) == 1).sum()

In [ ]:
remainder_word_dict = {}
# find possible words
def get_remainder_words(row):
    
    # existing letters
    inclusive_id_list = []
    for l in row['letters']:
        l_idx = letter_dict[l]        
        inclusive_id_list.append(word_id_list[char_matrix[:, l_idx] == 0])

    #print(inclusive_id_list)
    inclusive_id_list = np.concatenate(inclusive_id_list)

    # remainder letters            
    remainder_id_list = []
    for l in row['remainder']:
        l_idx = letter_dict[l]
        remainder_id_list.append(word_id_list[char_matrix[:, l_idx] == 0])
    
    remainder_id_list = np.concatenate(remainder_id_list)
    
    outcome_ids = np.setdiff1d(remainder_id_list, inclusive_id_list)
    return outcome_ids.shape[0]

In [ ]:
remainder.iloc[:2].apply(get_remainder_words, axis = 1)

In [ ]:
def convert_binary()

In [ ]:
# convert letters binary

In [ ]:
word_df['lid'] = word_df['lcase'].map(lambda x: int(''.join([letter_dict[w] for x in x])))

In [ ]:
'bread' & 'beard'

In [ ]:
def add_that_shit(m1, m2):
    ps = m1[:, None, :] + m2[None, :, :]
    matching_pairs = np.argwhere(ps.max(axis = 2) == 1)
    matching_pairs = matching_pairs[:int(matching_pairs.shape[0] /  2) , :]       
    outcome = m1[matching_pairs[:, 0]] + m2[matching_pairs[:, 1]]
    return outcome, matching_pairs

In [ ]:
r1, mp1 = add_that_shit(m1 = char_matrix, m2 = char_matrix)

In [ ]:
r1.shape

In [ ]:
r_list = []
mp_list = []
chunker1 = np.arange(start = 0, stop = r1.shape[0] + 10000,step = 10000 )
for icc, curr_chunk in enumerate(chunker1[:-1]):    
    
    next_chunk = chunker1[icc + 1]
    print('l1', curr_chunk, next_chunk)
    r2, mp2 = add_that_shit(m1 = r1[curr_chunk:next_chunk, :], m2 = char_matrix)
    print('l1', r2.shape)
    r_list.append(r2)
    mp_list.append(mp2)

In [ ]:

    chunker2 = np.arange(start = 0, stop = r2.shape[0] + 10000,step = 10000 )
    for icc2, cc2 in enumerate(chunker2[:-1]):
        nc2 = chunker2[icc2 + 1]
        print('l2', cc2, nc2)
        r3, mp3 = add_that_shit(m1 = r2[cc2:nc2, :], m2 = char_matrix)
        print('l2', r3.shape)

        chunker3 = np.arange(start = 0, stop = r3.shape[0] + 10000,step = 10000)
        for icc3, cc3 in enumerate(chunker3[:-1]):
            nc3 = chunker3[icc3 + 1]
            print('l3', cc3, nc3)
            r4, mp4 = add_that_shit(m1 = r3[cc3:nc3, :], m2 = char_matrix)
            print('l4', r4.shape)
            if r4.size != 0:
                r_list.append([r1, r2, r3, r4])
                mp_list.append([mp1, mp2, mp3, mp4])

In [ ]:
word_df['lcase_set'] = word_df['lcase'].map(lambda x: set(x))
word_df['lcase_tuple'] = word_df['lcase_set'].map(lambda x: tuple(x))

In [ ]:
# build dictionaries
word_dict = {}
for i_row, my_row in word_df.iterrows():
    word_dict[my_row['lcase']] = my_row['lcase_set']

In [ ]:
r1 = add_that_shit(m1 = char_matrix, m2 = char_matrix)

In [ ]:
edge_list = []
for lc0, lc1 in combinations(word_df['lcase'], 2):
    if word_dict[lc0].isdisjoint(word_dict[lc1]):
        #edge_list.append([ms[0], ms[1]])
        myg.add_edge(u_of_edge=lc0, v_of_edge=lc1)

In [ ]:
import networkx as nx
from itertools import combinations

In [ ]:
myg = nx.Graph()
edge_list = []
for lc0, lc1 in combinations(word_df['lcase'], 2):
    if word_dict[lc0].isdisjoint(word_dict[lc1]):
        #edge_list.append([ms[0], ms[1]])
        myg.add_edge(u_of_edge=lc0, v_of_edge=lc1)

In [ ]:
for r0 in char_matrix:

In [ ]:
import scipy

In [ ]:
scipy.special.comb(word_df.shape[0], k = 5, exact=True)

In [ ]:
# chunks of 10K
chunker = range(0, r1.shape[0] + 10000, 10000)
list(chunker)

In [ ]:
# get the first words

In [ ]:
lm0 = char_matrix.copy()

In [ ]:
grand_output_list = []
for ii, l0 in enumerate(lm0[:10, :]):
    print(ii, l0)    
    outcome = ((lm0 + l0) <= 1).all(axis = 1)
    lm1 = lm0[outcome, :]
    for l1 in lm1:
        outcome = ((lm1 + l1) <= 1).all(axis = 1)
        lm2 = lm1[outcome, :]
        for l2 in lm2:
            outcome = ((lm2 + l2) <= 1).all(axis = 1)
            lm3 = lm2[outcome, :]
            for l3 in lm3:
                outcome = ((lm3 + l3) <= 1).all(axis = 1)
                lm4 = lm3[outcome, :]
                if lm4.shape[0] > 0:
                    grand_output_list.append([l0, l1, l2, l3, l4])

In [ ]:
ncm = char_matrix[outcome, :]
for irow in ncm:

In [ ]:
testo

In [ ]:
# thinking about this wrong... it's a case of letters left....

In [ ]:
word_df.head()

In [ ]:
word_df['lcase_set'] = word_df['lcase'].map(lambda x: set(x))
word_df['lcase_tuple'] = word_df['lcase_set'].map(lambda x: tuple(x))

In [ ]:
# build dictionaries
word_dict = {}
for i_row, my_row in word_df.iterrows():
    word_dict[my_row['lcase']] = my_row['lcase_set']

In [ ]:
import networkx as nx
from itertools import combinations

In [ ]:
myg = nx.Graph()
edge_list = []
for lc0, lc1 in combinations(word_df['lcase'], 2):
    if word_dict[lc0].isdisjoint(word_dict[lc1]):
        #edge_list.append([ms[0], ms[1]])
        myg.add_edge(u_of_edge=lc0, v_of_edge=lc1)

In [ ]:
myg.number_of_edges()

In [ ]:
word_df.head()

In [ ]:
nx.__version__

In [ ]:
#myg_backup = myg.copy()

In [ ]:
# get 100 words
test_list = word_df['lcase'].tolist()[:10]

In [ ]:
test_list

In [ ]:
#myg = myg_backup.copy()
output_list = []
for w0 in word_df['lcase']:    
#for w0 in test_list:
    reject_groupings = set()
    print(w0)
    l0 = [w0, '', '', '', '']
    #output_list.append(l0)        
    # this is immediately adjacent
    w1_set = set(nx.neighbors(G = myg, n = w0))
    fl0 = set(w0)    
    for w1 in w1_set:
        if reject_groupings.isdisjoint(permutations((w0, w1), r = 2)):
            if fl0.isdisjoint(set(w1)):
                fl1 = fl0.copy()
                fl1.update(w1)                 
                l1 = l0[:]
                l1[1] = w1
                #output_list.append(l1)                
                # immediately adjacent candidates        
                w2_set = set(nx.neighbors(G = myg, n = w1))
                w2_set = w2_set.intersection(w1_set)                
                if w2_set:
                    for w2 in w2_set:
                        if reject_groupings.isdisjoint(permutations((w0, w1,w2), r = 2)):
                            if fl1.isdisjoint(set(w2)):
                                fl2 = fl1.copy()
                                fl2.update(w2)
                                l2 = l1[:]
                                l2[2] = w2
                                #output_list.append(l2)                        
                                w3_set = set(nx.neighbors(G = myg, n = w2))                        
                                w3_set = w3_set.intersection(w2_set)                                
                                if w3_set:
                                    for w3 in w3_set:
                                        if reject_groupings.isdisjoint(permutations((w0, w1, w2, w3), r = 2)):                                        
                                            if fl2.isdisjoint(set(w3)):
                                                fl3 = fl2.copy()
                                                fl3.update(w3)
                                                l3 = l2[:]
                                                l3[3] = w3
                                                #output_list.append(l3)    
                                                # print(l3)
                                                w4_set = set(nx.neighbors(G = myg, n = w3))
                                                w4_set = w4_set.intersection(w3_set)
                                                if w4_set:
                                                    for w4 in w4_set:
                                                        if reject_groupings.isdisjoint(permutations((w0, w1, w2, w3, w4), r = 2)):
                                                            if fl3.isdisjoint(set(w4)):
                                                                fl4 = fl3.copy()
                                                                fl4.update(w4)
                                                                l4 = l3[:]
                                                                l4[4] = w4
                                                                output_list.append(l4)    
                                                                print(l4)
                                                else:                                                    
                                                    # compute combos                                                                                                    
                                                    #print(l3)
                                                    #print(w0, w1, w2, w3)
                                                    perms = list(permutations(l3, r = 2))
                                                    #print(perms)
                                                    reject_groupings.update(perms)
                                                    myg.remove_edges_from(perms)


#print('yay')  
#reject_groupings

In [ ]:
output_list

In [ ]:
len(reject_groupings)

In [ ]:
myg.number_of_edges()

In [ ]:
output_list

In [ ]:
w3_seta

In [ ]:
reject_groupings

In [ ]:
len(testo)

In [ ]:
next_nodes

In [ ]:
myg.nodes(data = 'abhor')

In [ ]:
# this needs to be a recursive function

In [ ]:
test_outcome = np.where(tv1 == 0)[0]

In [ ]:
test_outcome

In [ ]:
outcome = char_matrix - tv1

In [ ]:
outcome

In [ ]:
outcome1 = outcome

In [ ]:
for wid in word_df['word_id'].tolist():
    cw = char_matrix[wid, :]
    
    # t/f list
    outcome = np.abs(char_matrix - cw).sum(1) == 10
    # next word id list
    wil2 = wil1[outcome]
    if wil2.shape[0] > 
    # next char matrix
    cm2 = cm1[outcome, :]
    
    
    # I'll need five different stages of the word_id_list 

    #

In [ ]:
)

In [ ]:
tv1 = char_matrix[0, :]

In [ ]:
tv2 = char_matrix[-1, :]

In [ ]:
tv3 = tv2 - tv1

In [ ]:
testo = char_matrix - tv1

In [ ]:
testo

In [ ]:
testo2 = testo[np.abs(testo).sum(1) == 10, :]

In [ ]:
testo2

In [ ]:
# step 2
testo = testo[testo.sum(0)  ]

In [ ]:
# for each row in the char_matrix:
# substract from the chart_matrix:

In [ ]:
np.abs(tv3).sum()

In [ ]:
word_df.iloc[0]

In [ ]:
word_df.iloc[-1]