In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(filepath_or_buffer='l5.txt', sep = '\t')

In [3]:
df.head()

,w1b,w2b,w3b,w4b,w5b,l2,l3,l4,l5
0,16912387,8914984,1344516,35668496,4202944,25827371,27171887,62840383,67043327
1,16912387,8914984,1344516,4202944,35668496,25827371,27171887,31374831,67043327
2,16912387,8914984,1351744,35668496,4195716,25827371,27179115,62847611,67043327
3,16912387,8914984,1351744,4195716,35668496,25827371,27179115,31374831,67043327
4,16912387,8914984,35668496,1344516,4202944,25827371,61495867,62840383,67043327

In [4]:
df.tail()

        w1b  w2b  w3b  w4b  w5b  l2  l3  l4  l5
999995   -1   -1   -1   -1   -1  -1  -1  -1  -1
999996   -1   -1   -1   -1   -1  -1  -1  -1  -1
999997   -1   -1   -1   -1   -1  -1  -1  -1  -1
999998   -1   -1   -1   -1   -1  -1  -1  -1  -1
999999   -1   -1   -1   -1   -1  -1  -1  -1  -1

In [7]:
df.dtypes

w1b    int64
w2b    int64
w3b    int64
w4b    int64
w5b    int64
l2     int64
l3     int64
l4     int64
l5     int64
dtype: object

In [9]:
df_out = df.loc[ df['w1b'] != -1, :].reset_index(drop = True)

In [10]:
df_out.shape

(27096, 9)

In [11]:
df_out.to_csv(path_or_buf='l5.txt', index = False)