In [1]:
# mike babb
# 2022 03 03 
# solve wordle

In [2]:
# standard
import pickle
import os
import sqlite3
from string import ascii_lowercase

In [3]:
import pandas as pd
import numpy as np

# load words

In [4]:
word_df = pd.read_csv(filepath_or_buffer='words_alpha.txt', header = None,
                      names = ['word'], dtype = 'str')

In [5]:
word_df['word'] = word_df['word'].astype(str)

In [6]:
# lower case
word_df['lcase'] = word_df['word'].str.lower()

In [7]:
word_df['lcase'].isna().value_counts()

lcase
False    370105
Name: count, dtype: int64

In [8]:
# count letters
word_df['nchars'] = word_df['lcase'].str.len()

In [9]:
word_df['n_unique_chars'] = word_df['lcase'].map(lambda x: len(set(x)))

In [10]:
word_df = word_df.loc[word_df['nchars'] == 5, ['lcase', 'n_unique_chars' ]].drop_duplicates().sort_values(by='lcase').reset_index(drop = True).reset_index(drop = False, names = ['word_id'])

In [11]:
word_df.head()

   word_id  lcase  n_unique_chars
0        0  aahed               4
1        1  aalii               3
2        2  aargh               4
3        3  aaron               4
4        4  abaca               3

In [12]:
# letter dict
letter_dict = {l:p for p,l in enumerate(ascii_lowercase)}

In [13]:
# build a char matrix
char_matrix = np.zeros(shape = (word_df.shape[0], 26), dtype = np.int8)

In [14]:
def fill_char_matrix(row):
    wid, word, nuc = row
    for l in word:
        char_matrix[wid, letter_dict[l]] += 1

    return None

In [15]:
word_df.head()

   word_id  lcase  n_unique_chars
0        0  aahed               4
1        1  aalii               3
2        2  aargh               4
3        3  aaron               4
4        4  abaca               3

In [16]:
output = word_df.apply(func = fill_char_matrix, axis = 1)

In [17]:
5 * word_df.shape[0]

79605

In [18]:
char_matrix.sum()

np.int64(79605)

In [19]:
# score words by letter
# count
letter_count = char_matrix.sum(axis = 0)

In [20]:
# multiply each row in the char matrix by the letter count vector
# and then sum, this is the score of each word
word_df['word_score'] = (char_matrix * letter_count).sum(axis = 1)

In [21]:
word_df.head()

   word_id  lcase  n_unique_chars  word_score
0        0  aahed               4       29686
1        1  aalii               3       31167
2        2  aargh               4       26186
3        3  aaron               4       31194
4        4  abaca               3       30015

In [22]:
word_df['word_score'].describe()

count    15921.000000
mean     23283.797437
std       4074.923892
min       8003.000000
25%      20523.000000
50%      23389.000000
75%      26105.000000
max      37537.000000
Name: word_score, dtype: float64

In [23]:
# gather the word id
word_id_list = word_df['word_id'].to_numpy(dtype = np.int16)

In [24]:
def suggest_words(toss_letters:str = None, 
                  known_pos:list = None, known_anti_pos:list = None, verbose:bool = True):
    """
    toss_letters: list. Letters known to be in the word
    known_pos: list. Letters in the correct position
    known_anti_pos: list. Letters in the incorrect position
    
    entering no values returns a list of suggested starting words, ranked by the frequency
    of each letter's occurence. Higher ranked words contain letters that occur more
    frequently across all five-digit words.    
    """    
       
    # intialize lists if necessary
    blank_count = 0
    
    if toss_letters is None:
        toss_letters = ['']*5
        blank_count += 1
    if known_pos is None:
        known_pos = ['']*5
        blank_count += 1    
    if known_anti_pos is None:
        known_anti_pos = ['']*5
        blank_count += 1
        
    for i_kap in range(len(known_anti_pos)):
        if known_pos[i_kap] != '':
            known_anti_pos[i_kap] = ''
    
    # check if the user supplied values
    if blank_count <3:
    
        # use this list to winnow down selections
        zero_id_list = np.zeros(shape = word_id_list.shape, dtype = int)
        
        # build the list of letters that are known
        keep_letters = set(known_pos)
        for kap in known_anti_pos:
            keep_letters = keep_letters.union(kap)
                               
        for kl in keep_letters:
            if kl != '':
                for jl in kl:
                    zero_id_list[char_matrix[:, letter_dict[jl]]>0] += 1
                
        # remove a word when there is an incorrect letter
        for tl in toss_letters:
            if tl != '':
                zero_id_list[char_matrix[:, letter_dict[tl]]>0] -= 1
        
        # this is the list of word_ids that have letters of interest
        curr_word_five_id_list = word_id_list[zero_id_list >= (len(keep_letters) - 1)]

        # select from the data frame based on the word id
        curr_df = word_df.loc[word_df['word_id'].isin(curr_word_five_id_list),
                          ['lcase', 'word_score', 'n_unique_chars']]

        # the list of possible words, after removing words with incorrect letters
        pos_words = curr_df['lcase'].values        

        # we're going to make use of the lists of letters with known positions
        # and letters known to be in the word, but in the incorrect post
        output_list = np.full(shape = pos_words.shape, fill_value=True)
        #print(known_pos)
        #print(known_anti_pos)
        # enumerate each word        
        for i_pos_word, pos_word in enumerate(pos_words):
            #print(pw)            
            # enumerate each character in each word
            for ii_pwl, i_pwl in enumerate(pos_word):
                # known positions
                # based on the index, remove the word if the letters do not match
                if known_pos[ii_pwl] != '':
                    #print(kp[ii_pw], i_pw)
                    if known_pos[ii_pwl] != i_pwl:
                        output_list[i_pos_word] = False
                # known anti-positions                
                # based on the index, remove the word if the letters do match
                if known_anti_pos[ii_pwl] != '':
                    curr_known_anti_pos = known_anti_pos[ii_pwl]
                    for jj_pwl in curr_known_anti_pos:
                        #print(kap[ii_pwl], i_pwl)
                        #known_anti_pos[ii_pwl]
                        if jj_pwl == i_pwl:
                            output_list[i_pos_word] = False
        
        # the list of possible words
        pos_words = pos_words[output_list]
        
        wdf = word_df.loc[word_df['lcase'].isin(pos_words), ['lcase', 'n_unique_chars', 'word_score']]
        wdf = wdf.sort_values(by = ['n_unique_chars', 'word_score'],
                                 ascending=False)
                
    else:
        # the initial list of words to choose from, sorted by unique characters and word score
        wdf = word_df.sort_values(by = ['n_unique_chars', 'word_score'],
                                 ascending=False)
    
    pos_words = wdf['lcase']
    pos_words = pos_words.tolist()
    if verbose:
        #print(len(pos_words))
        print(pos_words)
    return len(pos_words)

In [37]:
# letters known to not be in the word
# can be a list any length
toss_letters = 'prayghtlen'

# letters in the correct position
# list with length five
kp = ['','o','','','s']
#kp = None

# letters in the word, but in the incorrect spot
# list with 
kap = ['c', '', '', 'f', ''] 
#kap = None

# iterate until a solution is found
suggest_words(toss_letters = toss_letters, known_pos = kp, known_anti_pos = kap)

['focus']

1

# RANK STARTING WORDS

In [ ]:
remove_word_list = []
kp = ['','','','','']
kap = ['', '', '', '', '']
prev_letter = word_df['lcase'].iloc[0][0]
for i_cw, cw in enumerate(word_df['lcase'].tolist()):

    # curr_letter = cw[0]
    # if prev_letter != curr_letter:
    #     print(curr_letter)
    #     prev_letter = curr_letter    

    #print(cw)
    outcome = suggest_words(toss_letters = cw, known_pos = kp, known_anti_pos = kap, verbose = False)
    remove_word_list.append([cw, outcome])
    if i_cw % 100 == 0:
        print(i_cw / len(word_df.shape))

In [ ]:
# what is the best word to start with?
best_start_word = pd.DataFrame(data = remove_word_list, columns = ['lcase', 'n_next_word'])

In [ ]:
best_start_word = best_start_word.sort_values(by = 'n_next_word')

In [ ]:
best_start_word.to_excel(excel_writer = 'start_words.xlsx', index = False)

In [ ]:
best_start_word.head(n=50)

In [ ]:
best_start_word.tail()